name: Deploy to GitHub Pages

# Runs on every push to master under the firmware tool path
on:
  push:
    branches:
      - master
    paths:
      - firmware_tool/**

jobs:
  build-and-deploy:
    if: github.repository == 'techfoundrynz/Pubmote'

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install dependencies
        working-directory: ./firmware_tool # Change to the firmware_tool directory
        run: corepack enable && pnpm i
        
      - name: Build
        working-directory: ./firmware_tool
        run: pnpm build
        
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: contactsimonwilson@gmail.com
          # Where static files are.
          build_dir: ./firmware_tool/dist
          # Which branch to push files.
          cname: pubmote.com

          
